POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer He2s6Ut5HdkI63B9v0wIDc

{
    "title": "Lorem Ipsum",
    "author": "Sit Amet",
    "url": "http://lorem.ipsum",
    "likes": 0,
    "user": "662689938187a4b1e3233aa6"
}